### ISSUE TITLE
Memory Leak When Reproducing SSD Trainning Model

### ISSUE THREAD

**Issue by khanabadosh** [weiliu89/caffe#416]
Hi @weiliu89 Thanks a lot for putting and supporting your algorithm here.

I am trying to reproduce the SSD training model in order to understand the architecture. However I am getting memory leak error.  free(): invalid next size (normal).

I am following the steps enumerated in Readme file for Training for generating data and running the python command.

python examples/ssd/ssd_pascal.py

Here is the backtrace for the leak:

```
#0  0x00007ffff5237428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff523902a in __GI_abort () at abort.c:89
#2  0x00007ffff52797ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff53922e0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5281e0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ffff5392438 "free(): invalid next size (normal)", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3865
#5  0x00007ffff528598c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00007fffec10e07c in cv::StdMatAllocator::deallocate(cv::UMatData*) const () from /usr/Software/opencv/lib/libopencv_core.so.3.1
#7  0x00007fffec0de0ed in cv::Mat::deallocate() () from /usr/Software/opencv/lib/libopencv_core.so.3.1
#8  0x00007ffff6df3ff1 in cv::Mat::release (this=0x7ffefdffa570) at /usr/Software/opencv/include/opencv2/core/mat.inl.hpp:682
#9  0x00007ffff6df3c96 in cv::Mat::~Mat (this=0x7ffefdffa570, __in_chrg=<optimized out>) at /usr/Software/opencv/include/opencv2/core/mat.inl.hpp:569
#10 0x00007ffff6ec106c in caffe::DataTransformer<float>::CropImage (this=0x2cac84a0, datum=..., bbox=..., crop_datum=0x7ffe9948abb0) at src/caffe/data_transformer.cpp:360
#11 0x00007ffff6ec1671 in caffe::DataTransformer<float>::CropImage (this=0x2cac84a0, anno_datum=..., bbox=..., cropped_anno_datum=0x7ffe9948ff10) at src/caffe/data_transformer.cpp:417
#12 0x00007ffff6f6322e in caffe::AnnotatedDataLayer<float>::load_batch (this=0x2cac5f20, batch=0x2cac62e0) at src/caffe/layers/annotated_data_layer.cpp:187
#13 0x00007ffff6f790ef in caffe::BasePrefetchingDataLayer<float>::InternalThreadEntry (this=0x2cac5f20) at src/caffe/layers/base_data_layer.cpp:87
#14 0x00007ffff701d20c in caffe::InternalThread::entry (this=0x2cac62c8, device=2, mode=caffe::Caffe::GPU, rand_seed=1922081101, solver_count=4, root_solver=false) at src/caffe/internal_thread.cpp:51
#15 0x00007ffff701ff07 in boost::_mfi::mf5<void, caffe::InternalThread, int, caffe::Caffe::Brew, int, int, bool>::operator() (this=0x2cad3428, p=0x2cac62c8, a1=2, a2=caffe::Caffe::GPU, a3=1922081101, a4=4, a5=false)
    at /usr/include/boost/bind/mem_fn_template.hpp:619
#16 0x00007ffff701fddf in boost::_bi::list6<boost::_bi::value<caffe::InternalThread*>, boost::_bi::value<int>, boost::_bi::value<caffe::Caffe::Brew>, boost::_bi::value<int>, boost::_bi::value<int>, boost::_bi::value<bool> >::operator()<boost::_mfi::mf5<void, caffe::InternalThread, int, caffe::Caffe::Brew, int, int, bool>, boost::_bi::list0> (this=0x2cad3438, f=..., a=...) at /usr/include/boost/bind/bind.hpp:596
#17 0x00007ffff701fcd4 in boost::_bi::bind_t<void, boost::_mfi::mf5<void, caffe::InternalThread, int, caffe::Caffe::Brew, int, int, bool>, boost::_bi::list6<boost::_bi::value<caffe::InternalThread*>, boost::_bi::value<int>, boost::_bi::value<caffe::Caffe::Brew>, boost::_bi::value<int>, boost::_bi::value<int>, boost::_bi::value<bool> > >::operator() (this=0x2cad3428) at /usr/include/boost/bind/bind_template.hpp:20
#18 0x00007ffff701fc86 in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf5<void, caffe::InternalThread, int, caffe::Caffe::Brew, int, int, bool>, boost::_bi::list6<boost::_bi::value<caffe::InternalThread*>, boost::_bi::value<int>, boost::_bi::value<caffe::Caffe::Brew>, boost::_bi::value<int>, boost::_bi::value<int>, boost::_bi::value<bool> > > >::run (this=0x2cad3270) at /usr/include/boost/thread/detail/thread.hpp:116
#19 0x00007fffe6ccc5d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#20 0x00007fffe17a66ba in start_thread (arg=0x7ffefdffb700) at pthread_create.c:333
#21 0x00007ffff530882d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

### My system configuration
Operating system: Ubuntu 16.04
Compiler: gcc version 5.4.0 20160609
CUDA version (if applicable): Cuda 8.0
CUDNN version (if applicable): CUDNN 5.1.5
BLAS: atlas
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7.12

Kindly let me know how to resolve this issue.
Thanks

**Comment by weiliu89** [comment]
Not sure. How did you install opencv?

**Comment by khanabadosh** [comment]
I am using pre-compiled library, Opencv version is 3.1. I have setup new training using Opencv 2.4.9 installed using apt-get. It is going smooth so far. Hopefully it works with this Opencv version.

**Comment by khanabadosh** [comment]
It worked with fresh installation of opencv. Thanks.
