### ISSUE TITLE
Undefined symbol in ./data/VOC0712/create_data.sh 

### ISSUE THREAD

**Issue by Fansiee** [weiliu89/caffe#421]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

Traceback (most recent call last):
  File "/home/cv/dl/caffe/data/VOC0712/../../scripts/create_annoset.py", line 7, in <module>
    from caffe.proto import caffe_pb2
  File "/home/cv/dl/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/cv/dl/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /opt/intel/mkl/lib/intel64/libmkl_sequential.so: undefined symbol: mkl_lapack_ps_dgetrf_small

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:Ubuntu 14.04
Compiler:
CUDA version (if applicable):8.0
CUDNN version (if applicable):5.1
BLAS:mkl
Python or MATLAB version (for pycaffe and matcaffe respectively):Python

**Comment by wliu-nuro** [comment]
Did you try `openblas`?

**Comment by weiliu89** [comment]
Did you try `openblas`?

**Comment by Fansiee** [comment]
After I install the openblas and switch to it, I can't pass the compile. 
I use the cmake to build it, and the error is:

CMake Error at cmake/Modules/FindOpenBLAS.cmake:55 (MESSAGE):
  Could not find OpenBLAS
Call Stack (most recent call first):
  cmake/Dependencies.cmake:92 (find_package)
  CMakeLists.txt:43 (include)

I already change the environment path, but it doesn't work. :(

**Comment by Fansiee** [comment]
I have tried openblas, but it is the same error.

**Comment by weiliu89** [comment]
`make clean` before you make it again?

**Comment by Fansiee** [comment]
I uninstall the mkl, and install openblas, but it doesn't work.
I can't make it anyway, so I reinstall the ubuntu, and reinstall the caffe.
This time I use the openblas, and this error disappears.
Thanks!
