### ISSUE TITLE
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by A-levy** [weiliu89/caffe#482]
Hello,when I ./data/VOC0712/creat_data.sh,there has an error.But I'm using a version of cuda8.0
Traceback (most recent call last):
  File "/home/smie/SSD/caffe/data/VOC0712/../../scripts/create_annoset.py", line 7, in <module>
    from caffe.proto import caffe_pb2
  File "/home/smie/levy/SSD/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/smie/levy/SSD/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by sujinpeng** [comment]
If you have downloaded the anaconda2, you can input export LD_LIBRARY_PATH=“home/your name/anaconda2/lib” to solve your problem
