### ISSUE TITLE
error when using "create_data.bat" to create lmdb files on windows

### ISSUE THREAD

**Issue by hualiang9488** [weiliu89/caffe#515]
hi:
I install the caffe-ssd-microsoft on windows successfully. Then I want to train the VOC0712 dataset, but when I run "caffe-ssd-microsoft\data\VOC0712\create_data.bat":
------------------------------------------------------------------------------
Creating trainval lmdb...
usage: create_annoset.py [-h] [--redo] [--anno-type ANNO_TYPE]
[--label-type LABEL_TYPE] [--backend BACKEND]
[--check-size] [--encode-type ENCODE_TYPE]
[--encoded] [--gray]
[--label-map-file LABEL_MAP_FILE] [--min-dim MIN_DIM]
[--max-dim MAX_DIM] [--resize-height RESIZE_HEIGHT]
[--resize-width RESIZE_WIDTH] [--shuffle]
[--check-label]
root listfile outdir exampledir
create_annoset.py: error: too few arguments
------------------------------------------------------------------------
then I found "create_annoset.py" needs 4 required arguments, then I add "create_data.bat" : 

%data_root_dir% ^
%data_root_dir%\%%s.txt ^
%data_root_dir%\%%s_%db% ^
%data_root_dir%\example 

but, the error information change to : 
--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\ssd\caffe-ssd-microsoft\scripts\create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "D:\miniconda\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "D:\miniconda\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2]
----------------------------------------------------------------------------------------

I dont know how to fix this , please help ~~ 
Thanks !!!

**Comment by roipony** [comment]
@hualiang9488 can you please refer to ssd-windows repo?
Thanks

**Comment by XipengLin** [comment]
same problem, have you solved the problem?

**Comment by ppxd6** [comment]
have you solved this problem
