### ISSUE TITLE
ssd protobuf execution error

### ISSUE THREAD

**Issue by Lucien7786** [weiliu89/caffe#586]
After compiled the caffe-ssd project completely in ubuntu 14.04, a protobuf error occurred as follow:

### Issue summary
lucien@lucien-System-Product-Name:~/caffe$ ./data/VOC0712/create_data.sh 
Traceback (most recent call last):
  File "/home/lucien/caffe/data/VOC0712/../../scripts/create_annoset.py", line 7, in <module>
    from caffe.proto import caffe_pb2
  File "/home/lucien/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/lucien/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/lucien/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/lucien/caffe/python/caffe/proto/caffe_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/lucien/anaconda2/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 50, in <module>
    from google.protobuf.pyext import _message
AttributeError: 'module' object has no attribute 'MutableMapping'
--------------------------------------
here is the similar issue solution suggested. [http://stackoverflow.com/questions/34276280/attributeerror-module-object-has-no-attribute-mutablemapping](url)
I had tried to update protobuf to version 3.0.0 or 3.2.0, using 'conda install' command, then the caffe project cannot be complied with some ‘protobuf newer version’ errors. And it did not work.

## other Info:
lucien@lucien-System-Product-Name:~/caffe$ protoc --version
libprotoc 2.5.0
lucien@lucien-System-Product-Name:~/caffe$ which protoc
/home/lucien/anaconda2/bin/protoc
lucien@lucien-System-Product-Name:~/caffe$ conda search proto*
Fetching package metadata .........
libprotobuf               *  2.5.0                         0  defaults        
                             3.0.0                         0  defaults        
                             3.2.0                         0  defaults        
protobuf                     2.6.1                    py27_0  defaults        
                          *  2.6.1                    py27_1  defaults 

lucien@lucien-System-Product-Name:~/caffe$ ldd '/home/lucien/anaconda2/lib/python2.7/site-packages/google/protobuf/pyext/_message.so' 
	linux-vdso.so.1 =>  (0x00007ffe579a2000)
	libmkl_rt.so => /home/lucien/anaconda2/lib/libmkl_rt.so (0x00007f71eafa5000)
	libstdc++.so.6 => /home/lucien/anaconda2/lib/libstdc++.so.6 (0x00007f71eac8e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f71ea965000)
	libgcc_s.so.1 => /home/lucien/anaconda2/lib/libgcc_s.so.1 (0x00007f71ea74f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f71ea530000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f71ea168000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c40789f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f71e9f64000)

### My system configuration
Operating system: Ubuntu 14.04
CUDA version (if applicable): cuda 8
CUDNN version (if applicable): cudnn 6
BLAS:openblas
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7

Waiting for your reply. Thank you. @weiliu89

**Comment by Lucien7786** [comment]
**After I changed the order of $PATH, I put the 'anaconda2/bin' path behind all, it works. @weiliu89** 
lucien@lucien-System-Product-Name:~$ echo $PATH
/usr/local/cuda-8.0/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin:/home/lucien/anaconda2/bin
lucien@lucien-System-Product-Name:~$ protoc --version
libprotoc 2.5.0
**lucien@lucien-System-Product-Name:~$ which protoc
/usr/bin/protoc**
lucien@lucien-System-Product-Name:~$ cd caffe
lucien@lucien-System-Product-Name:~/caffe$ ./data/VOC0712/create_data.sh 
/home/lucien/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/lucien/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/lucien/data/VOCdevkit/ /home/lucien/caffe/data/VOC0712/../../data/VOC0712/test.txt /home/lucien/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
I0512 18:12:47.140281  2345 convert_annoset.cpp:122] A total of 4952 images.
I0512 18:12:47.141713  2345 db_lmdb.cpp:35] Opened lmdb /home/lucien/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
I0512 18:12:50.579589  2345 convert_annoset.cpp:195] Processed 1000 files.
I0512 18:12:53.950496  2345 convert_annoset.cpp:195] Processed 2000 files.
I0512 18:12:57.429944  2345 convert_annoset.cpp:195] Processed 3000 files.
I0512 18:13:00.796270  2345 convert_annoset.cpp:195] Processed 4000 files.
I0512 18:13:04.070722  2345 convert_annoset.cpp:201] Processed 4952 files.
/home/lucien/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/lucien/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/lucien/data/VOCdevkit/ /home/lucien/caffe/data/VOC0712/../../data/VOC0712/trainval.txt /home/lucien/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
I0512 18:13:04.558941  2367 convert_annoset.cpp:122] A total of 16551 images.
I0512 18:13:04.559188  2367 db_lmdb.cpp:35] Opened lmdb /home/lucien/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
I0512 18:13:08.763041  2367 convert_annoset.cpp:195] Processed 1000 files.
I0512 18:13:12.868752  2367 convert_annoset.cpp:195] Processed 2000 files.
I0512 18:13:17.167520  2367 convert_annoset.cpp:195] Processed 3000 files.
I0512 18:13:21.252336  2367 convert_annoset.cpp:195] Processed 4000 files.
I0512 18:13:25.378211  2367 convert_annoset.cpp:195] Processed 5000 files.
I0512 18:13:29.517325  2367 convert_annoset.cpp:195] Processed 6000 files.
I0512 18:13:33.771291  2367 convert_annoset.cpp:195] Processed 7000 files.
I0512 18:13:37.931638  2367 convert_annoset.cpp:195] Processed 8000 files.
I0512 18:13:41.993742  2367 convert_annoset.cpp:195] Processed 9000 files.
I0512 18:13:46.154719  2367 convert_annoset.cpp:195] Processed 10000 files.
I0512 18:13:50.264427  2367 convert_annoset.cpp:195] Processed 11000 files.
I0512 18:13:54.504400  2367 convert_annoset.cpp:195] Processed 12000 files.
I0512 18:13:58.659149  2367 convert_annoset.cpp:195] Processed 13000 files.
I0512 18:14:02.840292  2367 convert_annoset.cpp:195] Processed 14000 files.
I0512 18:14:07.024538  2367 convert_annoset.cpp:195] Processed 15000 files.
I0512 18:14:11.060233  2367 convert_annoset.cpp:195] Processed 16000 files.
I0512 18:14:13.329037  2367 convert_annoset.cpp:201] Processed 16551 files.
