### ISSUE TITLE
error: run "python examples/ssd/ssd_pascal_video.py"

### ISSUE THREAD

**Issue by Jimjipeng** [weiliu89/caffe#606]
Traceback (most recent call last):
  File "examples/ssd/ssd_pascal_video.py", line 2, in <module>
    import caffe
  File "/home/ubuntu/xjp/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ubuntu/xjp/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

**Comment by Jimjipeng** [comment]
echo "export PYTHONPATH=/home/ubuntu/xjp/caffe/python:/home/ubuntu/xjp/caffe/python/caffe/" >> ~/.bashrc

**Comment by superhector2000** [comment]
after
make -j8
# Make sure to build py and pycaffe
make py
