### ISSUE TITLE
"import caffe" error

### ISSUE THREAD

**Issue by deokisys** [weiliu89/caffe#660]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
install caffe completely 
in every make -j8, make py, make test-j8 and make runtest -j8

Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: cairo_surface_get_device_scale

how can "import caffe"?
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: ubuntu 14.0.4
Compiler:
CUDA version (if applicable): 7.5
CUDNN version (if applicable):5005
BLAS: OpenBLAS 0.2.20.dev 
Python or MATLAB version (for pycaffe and matcaffe respectively):python 2.7.12

**Comment by wematan** [comment]
Try:
make pycaffe
and then
export PYTHONPATH=$PYTHONPATH:/path/to/caffe/python
