### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LabelMap'

### ISSUE THREAD

**Issue by sravanitiger** [weiliu89/caffe#661]
Hello,

I'm trying to create the LMDB file and I'm running into this issue:

```
$ ./data/VOC0712/create_data.sh 
Traceback (most recent call last):
  File "/raid/users/Sravani/caffe-ssd/data/VOC0712/../../scripts/create_annoset.py", line 106, in <module>
    label_map = caffe_pb2.LabelMap()
AttributeError: 'module' object has no attribute 'LabelMap'
Traceback (most recent call last):
  File "/raid/users/Sravani/caffe-ssd/data/VOC0712/../../scripts/create_annoset.py", line 106, in <module>
    label_map = caffe_pb2.LabelMap()
**AttributeError: 'module' object has no attribute 'LabelMap'**
```

Here is what I tried to fix the issue:

1) I added this line to the .bashrc:
`export PYTHONPATH=/raid/users/Sravani/caffe-ssd/python/caffe:$PYTHONPATH`

2) I ran 'make pycaffe' in the caffe-ssd directory. 

3) I added this line to the create_annoset.py:
`sys.path.append("/raid/users/Sravani/caffe-ssd/python/caffe")`

I still can't get it to work without giving an error. Any help would be much appreciated.

**Comment by FumingX** [comment]
I did the same but still not working

**Comment by fbadaud** [comment]
hello 
 from previous post I think you should
 1. export PYTHONPATH=/raid/users/Sravani/caffe-ssd/python:$PYTHONPATH

 Anyway I do this and use the github.com/weiliu89/caffe.git  instead of the BVLC/caffe.git  and I still have this issue. when running create_data.sh 
So I don't know either how to get a fix for this
