### ISSUE TITLE
After adding a new layer, "net.to_proto()" gets "TypeError: Not a cmessage"

### ISSUE THREAD

**Issue by FlyingQianMM** [weiliu89/caffe#662]
Dear weiliu,

I define a new layer in ssd framwork, then the compilation and installation are successful. But when run examples/ssd/ssd_pascal.py, there are errors:

Traceback (most recent call last):
  File "examples/ssd/ssd_pascalr.py", line 393, in <module>
    print(net.to_proto(), file=f)
  File "/home/qianhui/caffe-ssd/python/caffe/net_spec.py", line 209, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/qianhui/caffe-ssd/python/caffe/net_spec.py", line 100, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/qianhui/caffe-ssd/python/caffe/net_spec.py", line 162, in _to_proto
    _param_names[self.type_name] + '_param'), k, v)
  File "/home/qianhui/caffe-ssd/python/caffe/net_spec.py", line 74, in assign_proto
    getattr(proto, name).extend(val)
TypeError: Not a cmessage

I followed the instructions for adding a new layers,  I don not know how to figure this problem out , did you encounter the same problems when adding new layers? Could you give me some advices? Thank your very much! 

Looking forward to hearing from you!

**Comment by FlyingQianMM** [comment]
I had found  initialization for one  parameter was wrong.
