### ISSUE TITLE
when run ssd_pascal.py,   AttributeError: 'str' object has no attribute '_to_proto'

### ISSUE THREAD

**Issue by frankzhan1992** [weiliu89/caffe#667]
Traceback (most recent call last):
  File "/home/frankzhan/caffe/examples/ssd/ssd_pascal_orig.py", line 466, in <module>
    print(net.to_proto(), file=f)
  File "/home/frankzhan/caffe/python/caffe/net_spec.py", line 209, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/frankzhan/caffe/python/caffe/net_spec.py", line 100, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/frankzhan/caffe/python/caffe/net_spec.py", line 142, in _to_proto
    inp._to_proto(layers, names, autonames)
AttributeError: 'str' object has no attribute '_to_proto'

I have searched, but I find no others have the same problem.

**Comment by liangxi627** [comment]
I have the same problem, have you soloved?

**Comment by cxm1995** [comment]
+1

**Comment by Betty-tkx** [comment]
+1

**Comment by dprosperino** [comment]
Hey Guys,

I don't know if this error is still a topic, however, I had the same error and in my case I debugged it by making sure that the layers are indeed caffe layers and not strings.
In my case I forgot to call a value, so it resulted in the program trying to concat a string to a caffe layer, which leads to this error.

I hope I could help.

Cheers,
d3lt4-papa
