### ISSUE TITLE
What's happening here? What should I do? 

### ISSUE THREAD

**Issue by yhz5256** [weiliu89/caffe#804]
/home/yang/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/yang/data/scenetext/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/yang/data/VOCdevkit/ /home/yang/data/scenetext/test.txt /home/yang/data/VOCdevkit/scenetext/lmdb/scenetext_test_lmdb
Traceback (most recent call last):
File "/home/yang/caffe/scripts/create_annoset.py", line 159, in
process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
/home/yang/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/yang/data/scenetext/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/yang/data/VOCdevkit/ /home/yang/data/scenetext/trainval.txt /home/yang/data/VOCdevkit/scenetext/lmdb/scenetext_trainval_lmdb
Traceback (most recent call last):
File "/home/yang/caffe/scripts/create_annoset.py", line 159, in
process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 710, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jianyin2016** [comment]
I met the same situation while making the LMDB files,seems to be caused by python OS error.by google the related info,i tried change the create_anoset.py line159 to process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE,shell=True)
then no warning occurred,but still failed to build the lmdb-files. @weiliu89 
btw,the creat_list.sh works well.

**Comment by JustVugg** [comment]
I have the same problem!Anyone find the solution?
